# Generated by Django 4.1.1 on 2023-07-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_autor', '0003_result_delete_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_autor.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_autor.question')),
            ],
        ),
    ]
